name: SimpleStatus
main: com.martinbrook.SimpleStatus.SimpleStatus
version: 0.12
description: A simple status plugin
commands:
 status:
  description: Update your status
  usage: /status | /status [message]
  aliases: st
 clearstatus:
  description: Clear your status
  usage: /clearstatus
  aliases: [cs, clear, back]
 afk:
  description: Set your status to AFK
  usage: /afk
 recording:
  description: Set your status to Recording
  usage: /recording
  aliases: rec 